version: "3"

services:
#######################
#        CMS          #
#######################

  server:
    image: node:9
    command: npm run backend
    working_dir: /app
    volumes:
      - ../server:/app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    links:
      - mongodb

  frontend:
    image: node:9
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "4000:4000"

  public:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
      - ../frontend/public:/var/www/cms-react
      - ../frontend/front.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    image: mongo
    ports:
      - "27017:27017"